#include<stdio.h>
int main()
{
    int i,j,n,bp,ap,c=0,k,a,b;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        for(j=n-1;j>=1;j--)
        {
            c=0;
            for(k=1;k<=j;k++)
            {
                if(j%k==0)
                {
                    c++;
                }
            }
            if(c==2)
            {
                bp=j;
                a=n-bp;
                break;
            }
        }
        for(j=n;j<=n+50;j++)
        {
            c=0;
            for(k=1;k<=j;k++)
            {
                if(j%k==0)
                {
                    c++;
                }
            }
            if(c==2)
            {
                ap=j;
                b=ap-n;
                break;
            }
        }
    }
    if(a<b)
    {
        printf("%d",a);
    }
    else
    {
        printf("%d",b);
    }
}